version: '4'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=${PORT}
      - MONGODB_URI_DEV=${MONGODB_URI_DEV}
      - MONGODB_URI_PROD=${MONGODB_URI_PROD}
      - JWT_SECRET=${JWT_SECRET}
      - HOST_EMAIL=${HOST_EMAIL}
      - ACCOUNT_EMAIL=${ACCOUNT_EMAIL}
      - PASSWORD_EMAIL=${PASSWORD_EMAIL}
      - NODE_ENV=production
    ports:
      - '4000:4000'
    command: node dist/main
    restart: unless-stopped
